### ISSUE TITLE
Show 'Loading..' message on first load of page

### ISSUE THREAD

**Issue by adunn49** [silverstripeltd/github-issue-search-client#24]
When first hitting the page the 'No result :(' message is shown whilst querying for results. Perhaps should show the 'Loading...' message as used when changing filters or performing new searches.

**Comment by robbieaverill** [comment]
![image](https://user-images.githubusercontent.com/5170590/54893150-5a57f000-4f19-11e9-8cb6-cead8a229370.png)

Looks like it's there now =)
