### ISSUE TITLE
Add "all bugs" mode

### ISSUE THREAD

**Issue by chillu** [silverstripeltd/github-issue-search-client#41]
It'll be a common search criteria, and shouldn't rely on users knowing about the `label:type/bug` trick

**Comment by sminnee** [comment]
We might want to exclude impact/low from this, to keep the volume manageable?

**Comment by robbieaverill** [comment]
I'm making a PR for this now but I haven't added the impact/low filter to it because I'm not sure I agree with doing that.

For reference, there are currently 225 low impact bugs out of 828. It would make things slightly more manageable but I'd argue it might be a bit confusing as well.

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripeltd/github-issue-search-client/pull/54
