### ISSUE TITLE
Filter by repo group

### ISSUE THREAD

**Issue by chillu** [silverstripeltd/github-issue-search-client#8]
By default, the search should cover all of our [supported modules](https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list/). Since we want to deploy this UI on both silverstripe.org and cwp.govt.nz, it would be good if we can filter to just "core" repositories for the silverstripe.org search. This would avoid confusion of what the "SilverStripe product" is to community members viewing search results through silverstripe.org.

I was thinking that we should have different "groups" of repositories defined in `.env`, and then instanciate the VueJS component with one or more groups. It might not need to be this open ended, since it's just two groups, so some hardcoding is fine. Ideally we don't code this into the build process, so we can run both variations off the same dist files.

**Comment by robbieaverill** [comment]
I think we just need to allow the "supported modules" checkbox to be permalinkable now. The repo groups and filter part exists already.

**Comment by chillu** [comment]
Yep, I think checkbox permalinking is the way to go, no need for more than two groups (= checkbox state)

**Comment by robbieaverill** [comment]
PR at #34
